/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package LibraryManagement;

import AdminLogin.AdminLogin;
import LibarianLogin.LibarianLogin;
import javax.swing.JFrame;

/**
 *
 * @author benndip
 */
public class LibraryManagement extends javax.swing.JFrame {

    /**
     * Creates new form LibraryManagement
     */
    public LibraryManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adminLoginBtn = new javax.swing.JButton();
        libarianLoginBtn = new javax.swing.JButton();
        Background_image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminLoginBtn.setFont(new java.awt.Font("Open Sans", 3, 15)); // NOI18N
        adminLoginBtn.setText("Admin Login");
        adminLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminLoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(adminLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 270, 80));

        libarianLoginBtn.setFont(new java.awt.Font("Open Sans", 3, 15)); // NOI18N
        libarianLoginBtn.setText("Libarian Login");
        libarianLoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libarianLoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(libarianLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 270, 70));

        Background_image.setIcon(new javax.swing.ImageIcon("/home/benndip/NetBeansProjects/LibraryManagement/src/main/java/LibraryManagement/LibraryManagement_background.png")); // NOI18N
        Background_image.setText("jLabel1");
        Background_image.setPreferredSize(new java.awt.Dimension(900, 500));
        getContentPane().add(Background_image, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void adminLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminLoginBtnActionPerformed
        // TODO add your handling code here:
        AdminLogin adminLogin = new AdminLogin();
        adminLogin.setVisible(true);
        adminLogin.pack();
        adminLogin.setLocationRelativeTo(null);
        adminLogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_adminLoginBtnActionPerformed

    private void libarianLoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libarianLoginBtnActionPerformed
        // TODO add your handling code here:
        LibarianLogin libarianLogin = new LibarianLogin();
        libarianLogin.setVisible(true);
        libarianLogin.pack();
        libarianLogin.setLocationRelativeTo(null);
        libarianLogin.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);        
    }//GEN-LAST:event_libarianLoginBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibraryManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibraryManagement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background_image;
    private javax.swing.JButton adminLoginBtn;
    private javax.swing.JButton libarianLoginBtn;
    // End of variables declaration//GEN-END:variables
}
