/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DeleteLibarian;

import com.mycompany.librarymanagement.DatabaseConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author benndip
 */
public class DeleteLibarian extends javax.swing.JFrame {

    /**
     * Creates new form DeleteLibarian
     */
    DatabaseConnection conn;
    public DeleteLibarian() {
        initComponents();
        conn = new DatabaseConnection();
        if(conn == null){
            JOptionPane.showMessageDialog(this, "Database Not available", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        libarianId = new javax.swing.JTextField();
        backBtn = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        libarianId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libarianIdActionPerformed(evt);
            }
        });
        getContentPane().add(libarianId, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 120, -1));

        backBtn.setText("Back");
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, -1, -1));

        Delete.setBackground(new java.awt.Color(146, 14, 254));
        Delete.setFont(new java.awt.Font("Ubuntu", 3, 12)); // NOI18N
        Delete.setForeground(new java.awt.Color(254, 254, 254));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 390, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon("/home/benndip/NetBeansProjects/LibraryManagement/src/main/java/DeleteLibarian/DeleteLibarian_background.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void libarianIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libarianIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libarianIdActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        // TODO add your handling code here:
        String sid=libarianId.getText();
	if(sid == null || sid.trim().equals("")){
            JOptionPane.showMessageDialog(this,"Id can't be blank");
	}
        else{
            int lid = Integer.parseInt(sid);
            int status = delete(lid);
            if(status > 0){
                JOptionPane.showMessageDialog(this,"Librarian deleted successfully!");
                libarianId.setText("");
            }
            else{
                JOptionPane.showMessageDialog(this,"No librarian with given id found");
            }
	}
    }//GEN-LAST:event_DeleteActionPerformed

    public int delete(int id){
		int status=0;
		try{
			Connection dbconn = conn.dbConnection();
			PreparedStatement ps=dbconn.prepareStatement("delete from libarians where id=?");
			ps.setInt(1,id);
			status = ps.executeUpdate();
			dbconn.close();
		}
                catch(Exception e)
                    {System.out.println(e);}
		return status;
	}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteLibarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteLibarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteLibarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteLibarian.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteLibarian().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField libarianId;
    // End of variables declaration//GEN-END:variables
}
